#!/bin/sh
#
# This script checks to make sure the database used by Neutron is at the
# correct version.  If the database is not at $NEUTRON_EXPECTED_DB_VERSION, as
# set in /etc/sysconfig/openstack-neutron, log an error and exit with an error
# code.
#
# This script is meant to be called from an init script or via ExecPreStart in
# a systemd unit.

[ -f /etc/sysconfig/openstack-neutron ] && . /etc/sysconfig/openstack-neutron

[ "$NEUTRON_EXPECTED_DB_VERSION" ] || exit 0

neutron_db_version=$(
	neutron-db-manage \
		--config-file /etc/neutron/neutron.conf \
		--config-file /etc/neutron/plugin.ini current 2>/dev/null |
	awk '{print $NF}')

if ! [ "$neutron_db_version" = "$NEUTRON_EXPECTED_DB_VERSION" ]; then
	logger -s -p daemon.error -t neutron-db-check \
		"ERROR: you must upgrade the neutron database before starting neutron services." 
	exit 1
fi

exit 0

